class RetryError(Exception):
    """Raised when a function fails after retrying a set number of times."""
